In [4]:
np=[1.0,10.4,3.2,5.1,7.5,2.7]

In [6]:
flotV=[np,np,np]

In [7]:
flotV

[[1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7],
 [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [8]:
flotV[0]='Python'

In [9]:
flotV

['Python', [1.0, 10.4, 3.2, 5.1, 7.5, 2.7], [1.0, 10.4, 3.2, 5.1, 7.5, 2.7]]

In [11]:
import numpy as np

In [12]:
a=np.array([1,2.5,4.0,5.5,7.0])

In [13]:
a[3:]

array([5.5, 7. ])

In [15]:
a.std()

2.1213203435596424

In [18]:
a.cumsum()

array([ 1. ,  3.5,  7.5, 13. , 20. ])

In [19]:
print(a)

[1.  2.5 4.  5.5 7. ]


In [20]:
print(a*2)

[ 2.  5.  8. 11. 14.]


In [21]:
print(a**2)

[ 1.    6.25 16.   30.25 49.  ]


In [22]:
print(np.sqrt(a))

[1.         1.58113883 2.         2.34520788 2.64575131]


In [25]:
b=np.array([a,a**2])

In [26]:
b

array([[ 1.  ,  2.5 ,  4.  ,  5.5 ,  7.  ],
       [ 1.  ,  6.25, 16.  , 30.25, 49.  ]])

In [27]:
b.sum(axis=0) #열끼리 더함

array([ 2.  ,  8.75, 20.  , 35.75, 56.  ])

In [28]:
b.sum(axis=1) #행끼리 더함

array([ 20. , 102.5])

In [31]:
import pandas as pd

In [33]:
pandas_series=pd.Series([3000,3200,2700],
                       index=['2016-11-10','2016-11-11','2016-11-12'])

In [34]:
print(type(pandas_series))

<class 'pandas.core.series.Series'>


In [35]:
pandas_series

2016-11-10    3000
2016-11-11    3200
2016-11-12    2700
dtype: int64

In [36]:
pandas_series[1:]

2016-11-11    3200
2016-11-12    2700
dtype: int64

In [37]:
df=pd.DataFrame([100,150,200,250,300],columns=['numbers'],
               index=['a','b','c','d','e'])

In [38]:
df

numbers
a      100
b      150
c      200
d      250
e      300

In [39]:
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [40]:
df.columns

Index(['numbers'], dtype='object')