In [1]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [2]:
iris=load_iris()

x_train=iris.data[:-30] #처음부터 뒤에서부터 30개까지 0~129 범위
y_train=iris.target[:-30]

x_test=iris.data[-30:]
y_test=iris.target[-30:]

In [3]:
print(y_train)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]


In [4]:
print(y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [5]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
rfc=RandomForestClassifier(n_estimators=10)
rfc

RandomForestClassifier(n_estimators=10)

In [8]:
rfc.fit(x_train,y_train)
prediction=rfc.predict(x_test)
print(prediction==y_test)

[ True False  True False  True  True False False  True False  True  True
  True False False  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True]


In [9]:
rfc.score(x_test,y_test)

0.7333333333333333

In [10]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [11]:
print('Accuracy is:',accuracy_score(prediction,y_test))
print('==============================================')
print(classification_report(prediction,y_test))

Accuracy is: 0.7333333333333333
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         8
           2       0.73      1.00      0.85        22

    accuracy                           0.73        30
   macro avg       0.37      0.50      0.42        30
weighted avg       0.54      0.73      0.62        30



C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
from sklearn.model_selection import train_test_split
x=iris.data
y=iris.target
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2)
print(y_test)
print(Y_test)

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]
[2 2 2 1 2 2 1 0 2 2 2 1 2 1 2 0 2 2 2 1 2 0 2 2 0 1 1 1 1 0]


In [15]:
clf=RandomForestClassifier(n_estimators=10)
clf.fit(X_train,Y_train)
prediction_1=clf.predict(X_test)
print('Accuracy is:',accuracy_score(prediction_1,Y_test))
print('==============================================')
print(classification_report(prediction,Y_test))

Accuracy is: 0.9666666666666667
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.33      0.38      0.35         8
           2       0.75      0.55      0.63        22

    accuracy                           0.50        30
   macro avg       0.36      0.31      0.33        30
weighted avg       0.64      0.50      0.56        30



C:\Users\user\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [17]:
clf_2=RandomForestClassifier(n_estimators=200,
                            max_features=4,
                            oob_score=True)
clf_2.fit(X_train,Y_train)
prediction_2=clf_2.predict(X_test)
print(prediction_2==Y_test)
print('Accuracy is:',accuracy_score(prediction_2,Y_test))
print('==============================================')
print(classification_report(prediction_2,Y_test))

[ True  True  True  True  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True]
Accuracy is: 0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      0.90      0.95        10
           2       0.94      1.00      0.97        15

    accuracy                           0.97        30
   macro avg       0.98      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [18]:
for feature,imp in zip(iris.feature_names,clf_2.feature_importances_):
    print(feature,imp)

sepal length (cm) 0.0162832739636682
sepal width (cm) 0.01137064143023683
petal length (cm) 0.4627656609321122
petal width (cm) 0.5095804236739828
