In [1]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

import pandas as pd
import numpy as np

In [2]:
tennis_data=pd.read_csv('C:/Users/user/Desktop/밀화부리/Python/playtennis.csv')
tennis_data

Outlook Temperature Humidity    Wind PlayTennis
0      Sunny         Hot     High    Weak         No
1      Sunny         Hot     High  Strong         No
2   Overcast         Hot     High    Weak        Yes
3       Rain        Mild     High    Weak        Yes
4       Rain        Cool   Normal    Weak        Yes
5       Rain        Cool   Normal  Strong         No
6   Overcast        Cool   Normal  Strong        Yes
7      Sunny        Mild     High    Weak         No
8      Sunny        Cool   Normal    Weak        Yes
9       Rain        Mild   Normal    Weak        Yes
10     Sunny        Mild   Normal  Strong        Yes
11  Overcast        Mild     High  Strong        Yes
12  Overcast         Hot   Normal    Weak        Yes
13      Rain        Mild     High  Strong         No

In [3]:
tennis_data.Outlook=tennis_data.Outlook.replace('Sunny',0)
tennis_data.Outlook=tennis_data.Outlook.replace('Overcast',1)
tennis_data.Outlook=tennis_data.Outlook.replace('Rain',2)

tennis_data.Temperature=tennis_data.Temperature.replace('Hot',3)
tennis_data.Temperature=tennis_data.Temperature.replace('Mild',4)
tennis_data.Temperature=tennis_data.Temperature.replace('Cool',5)

tennis_data.Humidity=tennis_data.Humidity.replace('High',6)
tennis_data.Humidity=tennis_data.Humidity.replace('Normal',7)

tennis_data.Wind=tennis_data.Wind.replace('Weak',8)
tennis_data.Wind=tennis_data.Wind.replace('Strong',9)

tennis_data.PlayTennis=tennis_data.PlayTennis.replace('No',10)
tennis_data.PlayTennis=tennis_data.PlayTennis.replace('Yes',11)

tennis_data

Outlook  Temperature  Humidity  Wind  PlayTennis
0         0            3         6     8          10
1         0            3         6     9          10
2         1            3         6     8          11
3         2            4         6     8          11
4         2            5         7     8          11
5         2            5         7     9          10
6         1            5         7     9          11
7         0            4         6     8          10
8         0            5         7     8          11
9         2            4         7     8          11
10        0            4         7     9          11
11        1            4         6     9          11
12        1            3         7     8          11
13        2            4         6     9          10

In [16]:
X=np.array(pd.DataFrame(tennis_data,columns=['Outlook','Temperature','Humidity','Wind']))
y=np.array(pd.DataFrame(tennis_data,columns=['PlayTennis']))
print(X)
print(y)

[[0 3 6 8]
 [0 3 6 9]
 [1 3 6 8]
 [2 4 6 8]
 [2 5 7 8]
 [2 5 7 9]
 [1 5 7 9]
 [0 4 6 8]
 [0 5 7 8]
 [2 4 7 8]
 [0 4 7 9]
 [1 4 6 9]
 [1 3 7 8]
 [2 4 6 9]]
[[10]
 [10]
 [11]
 [11]
 [11]
 [10]
 [11]
 [10]
 [11]
 [11]
 [11]
 [11]
 [11]
 [10]]


In [11]:
X_train,X_test,y_train,y_test=train_test_split(X,y)

In [17]:
print('X_train:',X_train)
print('X_test:',X_test)
print('y_train:',y_train)
print('y_test:',y_test)

X_train: [[1 5 7 9]
 [0 4 7 9]
 [2 5 7 9]
 [0 5 7 8]
 [2 4 7 8]
 [2 4 6 8]
 [0 4 6 8]
 [2 4 6 9]
 [1 3 6 8]
 [1 3 7 8]]
X_test: [[0 3 6 9]
 [2 5 7 8]
 [1 4 6 9]
 [0 3 6 8]]
y_train: [[11]
 [11]
 [10]
 [11]
 [11]
 [11]
 [10]
 [10]
 [11]
 [11]]
y_test: [[10]
 [11]
 [11]
 [10]]


In [18]:
gnb_clf=GaussianNB()
gnb_clf=gnb_clf.fit(X_train,y_train)

C:\Users\user\anaconda3\lib\site-packages\sklearn\utils\validation.py:73: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [19]:
gnb_prediction=gnb_clf.predict(X_test)

In [20]:
print(gnb_prediction) #11=Yes,10=No

[11 11 10 11]


In [21]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

In [22]:
print('Confusion Matrix')
print(confusion_matrix(y_test,gnb_prediction))

Confusion Matrix
[[0 2]
 [1 1]]


In [23]:
#confusion Matrix
#0<-실제는 10인데 예측값이 10이라고 나온 수:0 ,2<-실제는 10인데 예측값이 11이라고 나온 수 2
#1<-실제는 11인데 예측값이 10이라고 나온 수 1 ,1<-실제는 11인데 예측값이 11이라고로 나온 수 1
# 세로축:원래값,가로축:예측된결과

In [24]:
print('Classification Report')
print(classification_report(y_test,gnb_prediction))

Classification Report
              precision    recall  f1-score   support

          10       0.00      0.00      0.00         2
          11       0.33      0.50      0.40         2

    accuracy                           0.25         4
   macro avg       0.17      0.25      0.20         4
weighted avg       0.17      0.25      0.20         4



In [26]:
fmeasure=round(f1_score(y_test,gnb_prediction,average='weighted'),2)
accuracy=round(accuracy_score(y_test,gnb_prediction,normalize=True),2)

In [28]:
df_nbclf=pd.DataFrame(columns=['Classifier','F-measure','Accuracy'])
df_nbclf.loc[len(df_nbclf)]=['Naive Bayes',fmeasure,accuracy]
df_nbclf

Classifier  F-measure  Accuracy
0  Naive Bayes        0.2      0.25